AWSTemplateFormatVersion: 2010-09-09
Description: AWS SAM Swagger.
Parameters:
  ArtifactBucket:
    Default: kaonashi-aws-sam-deploy-dev
    Type: String
  Env:
    Default: dev
    Type: String
Resources:
  EmployeesFunction:
    Properties:
      CodeUri: s3://kaonashi-aws-sam-deploy-test-dev/b284997dbb43962490c0def1645bf7d4
      Events:
        ApiProxy:
          Properties:
            Method: GET
            Path: /employees
            RestApiId:
              Ref: KaonashiApi
          Type: Api
      Handler: employees.get
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: python3.6
    Type: AWS::Serverless::Function
  KaonashiApi:
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Sub: s3://${ArtifactBucket}/swagger.yaml
      StageName: dev
    Type: AWS::Serverless::Api
  LambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action: cloudwatch:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: lambda_cw_policy
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
