AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Swagger.

Parameters:
  Env:
    Type: String
    Default: dev
  ArtifactBucket:
    Type: String
    Default: kaonashi-aws-sam-deploy-dev
Resources:
  KaonashiApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub s3://${ArtifactBucket}/swagger.yaml
  EmployeesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: employees.get
      CodeUri: src/domain/employees
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiProxy:
          Type: Api
          Properties:
            RestApiId: !Ref KaonashiApi
            Path: /employees
            Method: GET
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "lambda_cw_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "cloudwatch:*"
                Resource: "*"